### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by AlphaFase** [Chatie/wechaty-getting-started#43]
```
⠹ [43/44] Installing node-expat@^2.3.15
WARN node unsupported "node@v6.14.2" is incompatible with xml2json@0.11.2 › joi@^13.1.2, expected node@>=8.9.0
⠸ [43/44] Installing topo@3.x.x
WARN node unsupported "node@v6.14.2" is incompatible with xml2json@0.11.2 › joi@13.4.0 › hoek@5.x.x, expected node@>=8.9.0
⠼ [43/44] Installing nan@^2.3.5
WARN node unsupported "node@v6.14.2" is incompatible with xml2json@0.11.2 › joi@13.4.0 › topo@3.x.x, expected node@>=8.0.0
⠸ [43/44] Installing punycode@2.x.xmake: Entering directory `/home/node/node_modules/_node-expat@2.3.16@node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
⠼ [43/44] Installing punycode@2.x.x../deps/libexpat/lib/xmlparse.c: In function ‘gather_time_entropy’:
../deps/libexpat/lib/xmlparse.c:780:7: warning: variable ‘gettimeofday_res’ set but not used [-Wunused-but-set-variable]
   int gettimeofday_res;
       ^
⠦ [43/44] Installing punycode@2.x.x  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
⠧ [43/44] Installing punycode@2.x.x  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
⠙ [43/44] Installing punycode@2.x.x  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
make: g++: Command not found
make: *** [Release/obj.target/node_expat/node-expat.o] Error 127
make: Leaving directory `/home/node/node_modules/_node-expat@2.3.16@node-expat/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.10.0-862.3.3.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node/node_modules/_node-expat@2.3.16@node-expat
gyp ERR! node -v v6.14.2
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
✖ Install fail! Error: Run "sh -c node-gyp rebuild" error, exit code 1
Error: Run "sh -c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (/usr/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

```

**Comment by lijiarui** [comment]
You node version should be 10 instead of 6.14.2

**Comment by lijiarui** [comment]
duplicate with https://github.com/lijiarui/wechaty-puppet-padchat/issues/114
