### ISSUE TITLE
 TypeError: _asyncToGenerator is not a function

### ISSUE THREAD

**Issue by csea007** [Chatie/wechaty-getting-started#49]
I encountered a issue when using the example file of tuling123-bot.js to process onMessage event

No matter what messages had been sent to robot, it reported same error:

02:42:17 ERR Wechaty onFunction(message) listener exception: TypeError: _asyncToGenerator is not a function
TypeError: _asyncToGenerator is not a function
    at Wechaty._onMessage (/bot/tuling.js:53:16)
    at Wechaty.onMessage (/bot/tuling.js:49:21)
    at Wechaty.on.args (/wechaty/src/wechaty.ts:538:18)
    at Wechaty.emit (events.js:182:13)
    at Wechaty.EventEmitter.emit (domain.js:442:20)
    at Wechaty.emit (/wechaty/src/wechaty.ts:304:18)
    at Wechaty.<anonymous> (/wechaty/src/wechaty.ts:646:18)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/wechaty.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Who can help me to take a look? Is it related to Babel? Thanks in advance.

**Comment by csea007** [comment]
this issue has been fixed after installed Babel related module,  close this issue
