### ISSUE TITLE
mock@latest, TypeError [ERR_INVALID_ARG_TYPE]: The "request" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by suntong** [Chatie/wechaty-getting-started#57]
I updated my wechaty environment to the latest today but found that `WECHATY_PUPPET=mock` is now broken:

Using the latest `wechaty-getting-started/examples/starter-bot.js` as the example:

```
$ node starter-bot.js
18:45:33 INFO Wechaty <default> start() v0.22.4 is starting...
Starter Bot Started.
```

I.e., AOK. Now run with  `WECHATY_PUPPET=mock`:

```
$ WECHATY_PUPPET=mock node starter-bot.js
18:45:53 INFO Wechaty <mock> start() v0.22.4 is starting...
18:45:53 INFO PuppetManager install(mock@latest) please wait ...
npm: + mock@0.1.1
added 1 package from 2 contributors and audited 1 package in 1.153s

npm: found 0 vulnerabilities

18:45:55 INFO PuppetManager install(mock@latest) done
TypeError [ERR_INVALID_ARG_TYPE]: The "request" argument must be of type string. Received type undefined
    at Function.resolve (internal/modules/cjs/helpers.js:28:13)
    at new mock (/path/to/node_modules/mock/index.js:15:29)
    at Function.<anonymous> (/path/to/node_modules/wechaty/dist/src/puppet-manager.js:58:34)
    at Generator.next (<anonymous>)
    at fulfilled (/path/to/node_modules/wechaty/dist/src/puppet-manager.js:4:58)

$ npm list --depth=0
├── qrcode-terminal@0.12.0
├── wechaty@0.22.4
├── wechaty-puppet-mock@0.14.2
└── wechaty-puppet-puppeteer@0.14.2

```

**Comment by zixia** [comment]
```diff
- $ WECHATY_PUPPET=mock node starter-bot.js
+ $ WECHATY_PUPPET=wechaty-puppet-mock node starter-bot.js
```

**Comment by zixia** [comment]
This is a bug in Wechaty: we did not validate the puppet name from the environment variable.

Currently, we have to use the full npm module name for puppet, instead of the abbr.

Learn full list of puppet providers at: <https://github.com/Chatie/wechaty-puppet/wiki/Directory>

**Comment by zixia** [comment]
Wechaty v0.23.6 should have added the check for this issue.

**Comment by suntong** [comment]
Gotya. Works like a charm!
